# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: 2stacks.net
email: 2stacks@2stacks.net
description: >- # this means to ignore newlines until "baseurl:"
  A Collection of Projects and Interests.
twitter_username: StanMan2Stacks
github_username: 2stacks
minimal_mistakes_skin: default
search: true
search_full_content: true
comments:
  provider: "disqus"
  disqus:
    shortname: "2stacks"

# SEO
google_site_verification: "xGzmpR56BcKfIDDfvqSTNBGxHe_2ibsCBu8yhJeOfX8"

# Analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-142280412-1"
    anonymize_ip: false # default

# Social Sharing
twitter:
  username: "StanMan2Stacks"

og_image: /assets/images/nanner_puss.jpg

social:
  links:
    - "https://twitter.com/StanMan2Stacks"
    - "https://github.com/2stacks"
    - "https://www.hackster.io/2stacks"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: US # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "2stacks"
  avatar : "/assets/images/nanner_puss.jpg"
  bio    : "A Collection of Projects and Interests."
  links:
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: mailto:2stacks@2stacks.net
    - label: "2stacks.net"
      icon: "fas fa-fw fa-link"
      url: "https://www.2stacks.net"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/StanMan2Stacks"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/2stacks"
    - label: "hackster.io"
      icon: "fab fa-fw fa-hackerrank"
      url: "https://www.hackster.io/2stacks"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/StanMan2Stacks"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/2stacks"
    - label: "hackster.io"
      icon: "fab fa-fw fa-hackerrank"
      url: "https://www.hackster.io/2stacks"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
